title: This is my blog
author: devtoor
email: jaymorales@protonmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm awesome
# social links
twitter_username: devtoor
github_username:  devtoor

show_excerpts: true # set to false to remove excerpts on the homepage

minima
